tasks:
  - init: |
      python -m pip install --upgrade pip
      pip install -r python_requirements.txt
      rfbrowser init
#      webdrivermanager chrome --linkpath /usr/local/bin
  - name: Start web server for RF logs
    init: python -m http.server 8000 -d logs

ports:
    - port: 8000
      onOpen: open-preview
    - port: 6080
      onOpen: open-preview

image: gitpod/workspace-full-vnc

vscode:
  extensions:
    - ms-python.python
    - ms-python.pylint
    - ms-python.black-formatter
    - robocorp.robotframework-lsp
    - techer.open-in-browser
    - eamodio.gitlens