tasks:
  - init: |
      python -m pip install --upgrade pip
      pip install -r python_requirements.txt
      rfbrowser init
#      webdrivermanager chrome --linkpath /usr/local/bin
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - ms-python.pylint
    - ms-python.black-formatter
    - robocorp.robotframework-lsp
    - techer.open-in-browser
    - eamodio.gitlens